<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-M7RBPII" failures="3" tests="4" name="Test" time="53.021" errors="0" timestamp="2025-05-29T22:58:51 IST">
  <testcase classname="testScript.LoginTest" name="verifyUserLoginWithInvalidCredentials" time="3.406">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testScript.LoginTest.verifyUserLoginWithInvalidCredentials(LoginTest.java:58)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserLoginWithInvalidCredentials -->
  <testcase classname="testScript.LoginTest" name="verifyUserLoginWithInvalidUsernameandValidPassword" time="0.23">
    <failure type="java.lang.IllegalStateException" message="Cannot get a NUMERIC value from a STRING cell">
      <![CDATA[java.lang.IllegalStateException: Cannot get a NUMERIC value from a STRING cell
at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:987)
at org.apache.poi.xssf.usermodel.XSSFCell.getNumericCellValue(XSSFCell.java:260)
at utitlities.ExcelUtility.getIntegerData(ExcelUtility.java:38)
at testScript.LoginTest.verifyUserLoginWithInvalidUsernameandValidPassword(LoginTest.java:40)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserLoginWithInvalidUsernameandValidPassword -->
  <testcase classname="testScript.LoginTest" name="verifyUserLoginWithValidUsernameAndInvalidPassword" time="12.968">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testScript.LoginTest.verifyUserLoginWithValidUsernameAndInvalidPassword(LoginTest.java:34)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserLoginWithValidUsernameAndInvalidPassword -->
  <testcase classname="testScript.LoginTest" name="verifyuserloginwithvalidcredentials" time="2.16"/>
</testsuite> <!-- Test -->
